version: '3.8'

services:
  meta-ads-mcp:
    build: .
    ports:
      - "8080:8080"
    environment:
      - META_ACCESS_TOKEN=${META_ACCESS_TOKEN}
      - PIPEBOARD_API_TOKEN=${PIPEBOARD_API_TOKEN:-}
      - META_APP_ID=${META_APP_ID:-}
      - META_APP_SECRET=${META_APP_SECRET:-}
      - MCP_LOG_LEVEL=${MCP_LOG_LEVEL:-INFO}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/mcp/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
